---
{{- if eq .Values.wxbotConfig.enable "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-imsdk-wxbot-pvc" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  {{- if eq .Values.global.scConfig.type "smb" -}}
  storageClassName: {{ printf "%s-%s" .Values.global.namespace .Values.global.scConfig.name }}
  {{- end -}}
  {{- if eq .Values.global.scConfig.type "raw" -}}
  storageClassName: {{ .Values.global.scConfig.name }}
  {{- end -}}
---
{{- end -}}