---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-imsdk-larkbot-service" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ printf "%s-imsdk-larkbot" .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ printf "%s-imsdk-larkbot" .Values.global.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-imsdk-wxbot-service" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ printf "%s-imsdk-wxbot" .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ printf "%s-imsdk-wxbot" .Values.global.namespace }}
---

