scConfig:
  secretName: "smb-secret"
  secretNamespace: "anywhere-door"
  source: "/anywhere-door"

images:
  mysqlImage: "mysql:latest"
  managerImage: "192.168.25.5:31100/maoyanluo/anywhere-door-manager:0.8.8"
  controlPlaneImage: "192.168.25.5:31100/maoyanluo/anywhere-door-control-plane:0.1.6"
  managerWebUiImage: "192.168.25.5:31100/maoyanluo/anywhere-door-manager-webui:0.2.4"

nodePorts:
  managerWebUiPort: 80

mysql:
  dbName: "anywhere_door"
  rootPassword: "p@ssword"

global:
  namespace: "anywhere-door"
  username: "maoyanluo"
  scConfig:
    name: "smb"
