anywhere-door-base:
  scConfig:
    secretName: "smb的secret名字"
    secretNamespace: "secret所在的名称空间"
    source: "smb的挂载点"
  
  images:
    mysqlImage: "mysql的镜像名字"
    managerImage: "后台管理的镜像名字"
    controlPlaneImage: "控制平面的镜像"
    managerWebUiImage: "控制平面webui的镜像"
  
  nodePorts:
    managerWebUiPort: 80
  
  mysql:
    dbName: "数据库名字"
    rootPassword: "数据库root账户密码"


anywhere-door-imsdks:
  images:
    larkbotImage: "larkbot镜像"
    wxbotImage: "wxbot镜像"
  
  larkbotConfig:
    token: "larkbot的令牌"
    name: "larkbot的名字"
    appId: "larkbot的app id"
    appSecret: "larkbot的app secret"
    openId: "larkbot的open id"
  
  wxbotConfig:
    adminWxid: "管理员的微信号"
    token: "wxbot的令牌"
    name: "wxbot的名字"
    apiGewe: "gewe的地址"


anywhere-door-plugins:
  images:
    aria2Image: "aria2插件镜像"
    glancesImage: "glances插件镜像"
    pveImage: "pve插件镜像"
    k8sImage: "k8s插件镜像"
  
  aria2Config:
    token: "aria2插件令牌"
    name: "aria2名称"
    aria2Rpc: "aria2 rpc地址"
    aria2Token: "aria2 令牌"
  
  glancesConfig:
    token: "glances插件令牌"
    name: "glances插件名称"
  
  pveConfig:
    token: "pve插件令牌"
    name: "pve插件名称"
  
  k8sConfig:
    token: "k8s插件令牌"
    name: "k8s插件名称"


global:
  namespace: "资源所在的k8s命名空间"
  username: "用户名"
  scConfig:
    name: "存储类的名称, 后续创建PV都会使用这个存储类"
