anywhere-door-base:
  scConfig:
    secretName: "smb-secret"
    secretNamespace: "anywhere-door"
    source: "/anywhere-door"
  
  images:
    mysqlImage: "mysql:latest"
    managerImage: "192.168.25.5:31100/maoyanluo/anywhere-door-manager:0.8.8"
    controlPlaneImage: "192.168.25.5:31100/maoyanluo/anywhere-door-control-plane:0.1.6"
    managerWebUiImage: "192.168.25.5:31100/maoyanluo/anywhere-door-manager-webui:0.2.4"
  
  nodePorts:
    managerWebUiPort: 80

anywhere-door-imsdks:
  images:
    larkbotImage: "192.168.25.5:31100/maoyanluo/anywhere-door-imsdk-larkbot:0.4.8"
    wxbotImage: "192.168.25.5:31100/maoyanluo/anywhere-door-imsdk-wxbot:0.4.4"
  
  larkbotConfig:
    enable: "false"
    appId: "app id"
    appSecret: "app secret"
    openId: "open id"
  
  wxbotConfig:
    enable: "false"
    adminWxid: "wxid"
    apiGewe: "http://gewe-api"


anywhere-door-plugins:
  images:
    aria2Image: "192.168.25.5:31100/maoyanluo/anywhere-door-plugin-aria2:0.9.4"
    glancesImage: "192.168.25.5:31100/maoyanluo/anywhere-door-plugin-glances:0.4.5"
    pveImage: "192.168.25.5:31100/maoyanluo/anywhere-door-plugin-pve:0.5.5"
    k8sImage: "192.168.25.5:31100/maoyanluo/anywhere-door-plugin-k8s:0.1.9"
  
  aria2Config:
    enable: "false"
    aria2Rpc: "http://aria2-rpc/json-rpc"
    aria2Token: "aria2-token"
  
  glancesConfig:
    enable: "false"
  
  pveConfig:
    enable: "false"
  
  k8sConfig:
    enable: "false"

global:
  username: "maoyanluo"
  scConfig:
    name: "smb"
