---
{{- if eq .Values.aria2Config.enable "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-plugin-aria2-service" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ printf "%s-plugin-aria2" .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ printf "%s-plugin-aria2" .Values.global.namespace }}
---
{{- end -}}
{{- if eq .Values.glancesConfig.enable "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-plugin-glances-service" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ printf "%s-plugin-glances" .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ printf "%s-plugin-glances" .Values.global.namespace }}
---
{{- end -}}
{{- if eq .Values.pveConfig.enable "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-plugin-pve-service" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ printf "%s-plugin-pve" .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ printf "%s-plugin-pve" .Values.global.namespace }}
---
{{- end -}}
{{- if eq .Values.k8sConfig.enable "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-plugin-k8s-service" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ printf "%s-plugin-k8s" .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ printf "%s-plugin-k8s" .Values.global.namespace }}
---
{{- end -}}
