---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-mysql-pvc" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  {{- if eq .Values.global.scConfig.type "smb" -}}
  storageClassName: {{ printf "%s-%s" .Values.global.namespace .Values.global.scConfig.name }}
  {{- end -}}
  {{- if eq .Values.global.scConfig.type "raw" -}}
  storageClassName: {{ .Values.global.scConfig.name }}
  {{- end -}}
---