---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-mysql-pvc" .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: {{ printf "%s-%s" .Values.global.namespace .Values.global.scConfig.name }}
---